# Generated by Django 6.0.3 on 2026-03-10 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dci', models.CharField(max_length=255)),
                ('forme', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField()),
                ('stock_minimum', models.IntegerField()),
                ('date_expiration', models.DateField()),
                ('ordonnance_requise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaments', to='categories.categorie')),
            ],
        ),
    ]
