# Generated by Django 6.0.3 on 2026-03-10 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='categories.categorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
    ]
